vich_uploader:
    db_driver: orm

    mappings:
        user_cv:
            uri_prefix: /uploads/cv
            upload_destination: '%kernel.project_dir%/var/uploads/cv'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        user_portfolio:
            uri_prefix: /uploads/portfolio
            upload_destination: '%kernel.project_dir%/var/uploads/portfolios'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        user_logo:
            uri_prefix: /uploads/logo
            upload_destination: '%kernel.project_dir%/var/uploads/logos'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
