vich_uploader:
    db_driver: orm

    mappings:
        user_cv:
            uri_prefix: /files/cv
            upload_destination: '%kernel.project_dir%/public/files/cvs'
            namer: Vich\UploaderBundle\Naming\OrignameNamer

        user_portfolio:
            uri_prefix: /files/portfolio
            upload_destination: '%kernel.project_dir%/public/files/portfolios'
            namer: Vich\UploaderBundle\Naming\OrignameNamer